version: '3'
services:

    web:
        image: testserver
        ports:
        - 8080:8080
        depends_on:
          - mongo
    mongo:
        image: mongo:latest
        container_name: "mongo"

